### ISSUE TITLE
API retirada do ar

### ISSUE THREAD

**Issue by felipemfp** [Projeto-SIAC/suap-wrapper#1]
Ao que parece, a [API](https://suap.ifrn.edu.br/api/docs) foi retirada do ar pelo equipe de desenvolvimento do __SUAP__. :disappointed: 

![Captura de tela de 2016-09-03 20-24-27](https://cloud.githubusercontent.com/assets/8146112/18228115/7191b8bc-7214-11e6-9f19-30064ce1b0c3.png)

**Comment by chicobentojr** [comment]
A API voltou ao que parece

**Comment by felipemfp** [comment]
Voltou sim.
