### ISSUE TITLE
Esse projeto ta vivo?

### ISSUE THREAD

**Issue by maykon-oliveira** [Projeto-SIAC/suap-wrapper#3]
Eu gostaria de contribuir, mas quero saber se eu mandar o pull request vai ter alguem pra aceitar.

**Comment by felipemfp** [comment]
Apesar de não precisar atualmente dele, aceitaremos pull requests sem problemas. Nós precisavámos apenas da **Autenticação**, mas seria interessante ter os outros recursos da API.

**Comment by maykon-oliveira** [comment]
Tambem acho legal adicionar outras coisas, então massa :+1: :
